name: cftime test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [windows-latest, ubuntu-latest, macos-latest]
        platform: [x64, x32]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }} ${{ matrix.os }}
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} numpy cython pip pytest pytest-cov --strict-channel-priority
        source activate TEST
        pip install -e . --no-deps --force-reinstall
        conda info --all
        conda list

    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        py.test -vv test
